# Generated by Django 3.1.3 on 2020-11-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
